# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73f68f3f4277ef0cd497622e5f0644663408e7c0d48d8a3e5f25f2966be2d207e955a02a9950f9755c76c9754931686ef0df2792f9ee1c5271ddb0613ef8ab9

test:
  secret_key_base: 9567b119725d3f86abb0d2d9be5e7c198558c9ceb02366517f170230505d41203c113d0b1691f61940655073f9f1d1c3e76387c4a0d5cc8f488d0725ee93ff11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
